// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3528.Simba.subsystems;

import org.usfirst.frc3528.Simba.RobotMap;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearShifter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Compressor driveTrainCompressor = RobotMap.driveTrainCompressor;
    DoubleSolenoid driveTrainShifter = RobotMap.driveTrainShifter;
    boolean isHighGear = true;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void switchUp() {
    	if (isHighGear) {
    		RobotMap.driveTrainShifter.set(DoubleSolenoid.Value.kForward);
    		isHighGear = false;
    	}
    }
    
    public void switchDown() {
    	if (!isHighGear) {
    		RobotMap.driveTrainShifter.set(DoubleSolenoid.Value.kReverse);
    		isHighGear = true;
    	}
    }
    
    public void switchOff() {
    	RobotMap.driveTrainShifter.set(DoubleSolenoid.Value.kOff);
    }
}
